### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by weituotian** [penhold3r/email-builder#1]
TypeError: Cannot read property 'properties' of undefined
    at module.exports (E:\projects\examples\email-builder\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at E:\projects\examples\email-builder\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (E:\projects\examples\email-builder\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by binomialstew** [comment]
Update webpack and webpack-cli:
https://github.com/webpack/webpack/issues/8082
